'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.VisualBasic.Data.GIS.Resources.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; height=&quot;1314&quot; id=&quot;svg2985&quot; version=&quot;1.1&quot; viewBox=&quot;82.992 45.607 2528.5721 1428.3294&quot; width=&quot;2560&quot;&gt;
        '''  &lt;title&gt;World Map&lt;/title&gt;
        '''  &lt;defs id=&quot;defs2987&quot;/&gt;
        '''  &lt;style id=&quot;style_css_sheet&quot; type=&quot;text/css&quot;&gt; 
        '''/*
        ''' * Below are Cascading Style Sheet (CSS) definitions in use in this file,
        ''' * which allow easily changing how countries are displayed.
        ''' *
        ''' */
        '''
        '''/*
        ''' * Circles around small countries
        ''' *
        ''' * Change opacity to 1 to display all circles.
        ''' *
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BlankMap_World6() As String
            Get
                Return ResourceManager.GetString("BlankMap_World6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to name,alpha2,alpha3,code
        '''Aruba,AW,ABW,533
        '''Afghanistan,AF,AFG,4
        '''Angola,AO,AGO,24
        '''Anguilla,AI,AIA,660
        '''&quot;Åland Islands&quot;,AX,ALA,248
        '''Albania,AL,ALB,8
        '''Andorra,AD,AND,20
        '''&quot;United Arab Emirates&quot;,AE,ARE,784
        '''Argentina,AR,ARG,32
        '''Armenia,AM,ARM,51
        '''&quot;American Samoa&quot;,AS,ASM,16
        '''Antarctica,AQ,ATA,10
        '''&quot;French Southern Territories&quot;,TF,ATF,260
        '''&quot;Antigua and Barbuda&quot;,AG,ATG,28
        '''Australia,AU,AUS,36
        '''Austria,AT,AUT,40
        '''Azerbaijan,AZ,AZE,31
        '''Burundi,BI,BDI,108
        '''Belgium,BE,BEL,56
        '''Benin,BJ,BEN,204
        '''&quot;Bonaire, Sint Eustatius [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ISO_3166_1() As String
            Get
                Return ResourceManager.GetString("ISO_3166_1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
